import { Inter } from 'next/font/google'
import './globals.css'
import ApolloWrapper from '@/lib/apollo-wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>{children}</ApolloWrapper>
        {children}
        
        </body>
    </html>
  )
}
